server:
  http: "\${SERVER_PORT:8080}"

spring:
  application:
    name: ${artifactId}
    version: ${version}
  jmx.enabled: true
  threads:
    virtual:
      enabled: "\${VIRTUAL_THREADS_ENABLED:true}"

management:
  info:
    build.enabled: true
    java.enabled: true
    git.enabled: true
  tracing:
    export: "\${TRACING_EXPORT:false}"
    sampling.probability: "\${TRACING_SAMPLING_PROBABILITY:1.0}"
    baggage.remote-fields:
      - X-user-id
  observations:
    http.server:
        filter.order: -100
  endpoints:
    jmx:
      exposure.include: "*"
    web:
      exposure:
        include: health, info, prometheus, metrics, caches
      base-path: /actuator
  endpoint:
    health:
      probes.enabled: true
      logging.slow-indicator-threshold: "\${HEALTH_ACTUATOR_LOGGER_TIMEOUT_DURATION:PT1S}"
      show-details: "\${HEALTH_ACTUATOR_SHOW_DETAILS:when-authorized}"
      group:
        readiness.include: "*"
        liveness.include: livenessState,diskSpace,ping
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${artifactId}
    export:
      prometheus:
        enabled: true
        step: 1m
        descriptions: true
    enable:
      jvm: true
      process: true
      system: true
      http: true
      logback: true

logging:
  level:
    root: "\${LOG_LEVEL_ROOT:INFO}"
    it.gov.pagopa: "\${LOG_LEVEL_PAGOPA:INFO}"
    org.springframework: "\${LOG_LEVEL_SPRING:INFO}"
    org.springframework.boot.availability: "\${LOG_LEVEL_SPRING_BOOT_AVAILABILITY:DEBUG}"
    it.gov.pagopa.payhub.pdnd.exception.PdndServicesExceptionHandler: "\${LOGGING_LEVEL_API_REQUEST_EXCEPTION:INFO}"
    org.springdoc.core.utils.SpringDocAnnotationsUtils: "\${LOG_LEVEL_SPRING_DOC:ERROR}"
    PERFORMANCE_LOG: "\${LOG_LEVEL_PERFORMANCE_LOG:INFO}"
    PERFORMANCE_LOG.API_REQUEST: "\${LOG_LEVEL_PERFORMANCE_LOG_API_REQUEST:\${logging.level.PERFORMANCE_LOG}}"
    PERFORMANCE_LOG.REST_INVOKE: "\${LOG_LEVEL_PERFORMANCE_LOG_REST_INVOKE:\${logging.level.PERFORMANCE_LOG}}"

springdoc:
  writer-with-default-pretty-printer: true

jwt:
  access-token:
    public-key: "\${JWT_TOKEN_PUBLIC_KEY:-----BEGIN PUBLIC KEY-----
                MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2ovm/rd3g69dq9PisinQ
                6mWy8ZttT8D+GKXCsHZycsGnN7b74TPyYy+4+h+9cgJeizp8RDRrufHjiBrqi/2r
                eOk/rD7ZHbpfQvHK8MYfgIVdtTxYMX/GGdOrX6/5TV2b8e2aCG6GmxF0UuEvxY9o
                TmcZUxnIeDtl/ixz4DQ754eS363qWfEA92opW+jcYzr07sbQtR86e+Z/s/CUeX6W
                1PHNvBqdlAgp2ecr/1DOLq1D9hEANBPSwbt+FM6FNe4vLphi7GTwiB0yaAuy+jE8
                odND6HPvvvmgbK1/2qTHn/HJjWUm11LUC73BszR32BKbdEEhxPQnnwswVekWzPi1
                IwIDAQAB
                -----END PUBLIC KEY-----}"

rest:
  defaults:
    connection-pool:
      size: "\${DEFAULT_REST_CONNECTION_POOL_SIZE:10}"
      size-per-route: "\${DEFAULT_REST_CONNECTION_POOL_SIZE_PER_ROUTE:5}"
      time-to-live-minutes: "\${DEFAULT_REST_CONNECTION_POOL_TIME_TO_LIVE_MINUTES:10}"
    timeout:
      connect-millis: "\${DEFAULT_REST_TIMEOUT_CONNECT_MILLIS:120000}"
      read-millis: "\${DEFAULT_REST_TIMEOUT_READ_MILLIS:120000}"
  pdnd:
    base-url: "\${PDND_BASE_URL:https://auth.uat.interop.pagopa.it}"
    max-attempts: "\${PDND_MAX_ATTEMPTS:3}" # It's counting also the first attempt
    wait-time-millis: "\${PDND_WAIT_TIME_MILLIS:500}"
    print-body-when-error: "\${PDND_PRINT_BODY_WHEN_ERROR:true}"
    default-client:
      client-id: "\${PDND_SERVICE_CLIENTID:clientid}"
      kid: "\${PDND_SERVICE_KID:kid}"
      private-key: "\${PDND_SERVICE_PRIVATEKEY:}"
      public-key: "\${PDND_SERVICE_PUBLICKEY:}"
    config:
      env: "\${ENV:dev}"
      user-id: "\${PDND_AUTH_USERID:pdnd-user}"
      audience: "\${PDND_ACCESS_TOKEN_AUDIENCE:auth.uat.interop.pagopa.it/client-assertion}"
      auth-expiration-minutes: "\${PDND_AUTH_EXPIRATION_MINUTES:10}"
  anpr:
    base-url: "\${ANPR_BASE_URL:http://p4pa-mocks-microservice-chart:8080}\${ANPR_SERVICES_BASE_PATH:/govway/rest/in/MinInternoPortaANPR-PDND}"
    max-attempts: "\${PDND_MAX_ATTEMPTS:3}" # It's counting also the first attempt
    wait-time-millis: "\${PDND_WAIT_TIME_MILLIS:500}"
    print-body-when-error: "\${PDND_PRINT_BODY_WHEN_ERROR:true}"
    default-client:
      client-id: "\${PDND_SERVICE_ANPR_CLIENTID:\${rest.pdnd.default-client.client-id}}"
      kid: "\${PDND_SERVICE_ANPR_KID:\${rest.pdnd.default-client.kid}}"
      private-key: "\${PDND_SERVICE_ANPR_PRIVATEKEY:\${rest.pdnd.default-client.private-key}}"
      public-key: "\${PDND_SERVICE_ANPR_PUBLICKEY:\${rest.pdnd.default-client.public-key}}"
    https:
      trust-all: "\${ANPR_TRUST_ALL:false}"
    services:
      c003:
        base-path: "\${PDND_SERVICE_ANPR_C003_BASE_PATH:/C003-servizioVerificaDichGeneralita/v1}"
        purpose-id: "\${PDND_SERVICE_ANPR_C003_PURPOSE_ID:c003purposeid}"
        audience: "\${PDND_SERVICE_ANPR_C003_AUDIENCE:C003audience}"
        client-id: "\${PDND_SERVICE_ANPR_C003_CLIENTID:\${rest.anpr.default-client.client-id}}"
        kid: "\${PDND_SERVICE_ANPR_C003_KID:\${rest.anpr.default-client.kid}}"
        private-key: "\${PDND_SERVICE_ANPR_C003_PRIVATEKEY:\${rest.anpr.default-client.private-key}}"
        public-key: "\${PDND_SERVICE_ANPR_C003_PUBLICKEY:\${rest.anpr.default-client.public-key}}"
      c030:
        base-path: "\${PDND_SERVICE_ANPR_C030_BASE_PATH:/C030-servizioAccertamentoIdUnicoNazionale/v1/}"
        purpose-id: "\${PDND_SERVICE_ANPR_C030_PURPOSE_ID:c030purposeid}"
        audience: "\${PDND_SERVICE_ANPR_C030_AUDIENCE:C030audience}"
        client-id: "\${PDND_SERVICE_ANPR_C030_CLIENTID:\${rest.anpr.default-client.client-id}}"
        kid: "\${PDND_SERVICE_ANPR_C030_KID:\${rest.anpr.default-client.kid}}"
        private-key: "\${PDND_SERVICE_ANPR_C030_PRIVATEKEY:\${rest.anpr.default-client.private-key}}"
        public-key: "\${PDND_SERVICE_ANPR_C030_PUBLICKEY:\${rest.anpr.default-client.public-key}}"
  send:
    base-url: "\${SEND_BASE_URL:https://api.uat.notifichedigitali.it}"
    service:
      base-path: "\${PDND_SERVICE_SEND_BASE_PATH:}"
      purpose-id: "\${PDND_SERVICE_SEND_PURPOSE_ID:purposeid}"
      client-id: "\${PDND_SERVICE_SEND_CLIENTID:\${PDND_SERVICE_CLIENTID:clientid}}"
      kid: "\${PDND_SERVICE_SEND_KID:\${PDND_SERVICE_KID:kid}}"
      private-key: "\${PDND_SERVICE_SEND_PRIVATEKEY:\${rest.pdnd.default-client.private-key}}"
      public-key: "\${PDND_SERVICE_SEND_PUBLICKEY:\${rest.pdnd.default-client.public-key}}"

cache:
  anpr-ids:
    size: "\${CACHE_ANPR_IDS_SIZE:1000}"
    expire-in: "\${CACHE_ANPR_IDS_MINUTES:60}"