microservice-chart:
  image:
    repository: p4paditncorecommonacr.azurecr.io/p4papdndservices
    tag: latest
    pullPolicy: Always

  ingress:
    host: "hub.internal.dev.p4pa.pagopa.it"

  resources:
    requests:
      memory: "256Mi"
      cpu: "40m"
    limits:
      memory: "4Gi"
      cpu: "300m"

  autoscaling:
    enable: false
  #    minReplica: 1
  #    maxReplica: 1
  #    pollingInterval: 30 # seconds
  #    cooldownPeriod: 300 # seconds
  #    triggers:
  #      - type: cpu
  #        metadata:
  #          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
  #          value: "70"

  envConfig:
    ENV: "DEV"
    JAVA_TOOL_OPTIONS: "-Xms128m -Xmx4g -Djava.util.concurrent.ForkJoinPool.common.parallelism=7 -javaagent:/app/applicationinsights-agent.jar -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json -agentlib:jdwp=transport=dt_socket,server=y,address=8001,suspend=n -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3002 -Dcom.sun.management.jmxremote.rmi.port=3003 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"

    PDND_BASE_URL: http://idpay-mock-microservice-chart:8080/idpay/mock/pdnd
    PDND_ACCESS_TOKEN_AUDIENCE: auth.uat.interop.pagopa.it/client-assertion

    #This should be removed once read from initiative
    PAGOPA_PDND_CONFIGURATION_CLIENT_ID: 5df9f218-df34-4f05-a9c4-e4a74b2a8e3f
    PAGOPA_PDND_CONFIGURATION_KID: r3ee8wZ39fxq71LinbYDgpoHeywbuzLyc4ynVldEAKY
    PAGOPA_PDND_CONFIGURATION_PURPOSE_ID: 8af4c795-8066-4407-a0b3-c95c2daefd6c

  keyvault:
    name: "p4pa-d-payhub-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"